//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLine.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandLine.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys in switch mappings are case-insensitive. A duplicated key &apos;{0}&apos; was found..
        /// </summary>
        internal static string Error_DuplicatedKeyInSwitchMappings {
            get {
                return ResourceManager.GetString("Error_DuplicatedKeyInSwitchMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch mappings contain an invalid switch &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidSwitchMapping {
            get {
                return ResourceManager.GetString("Error_InvalidSwitchMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short switch &apos;{0}&apos; is not defined in the switch mappings..
        /// </summary>
        internal static string Error_ShortSwitchNotDefined {
            get {
                return ResourceManager.GetString("Error_ShortSwitchNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument format: &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnrecognizedArgumentFormat {
            get {
                return ResourceManager.GetString("Error_UnrecognizedArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for switch &apos;{0}&apos; is missing..
        /// </summary>
        internal static string Error_ValueIsMissing {
            get {
                return ResourceManager.GetString("Error_ValueIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys in switch mappings are case-insensitive. A duplicated key &apos;{0}&apos; was found..
        /// </summary>
        internal static string FormatError_DuplicatedKeyInSwitchMappings {
            get {
                return ResourceManager.GetString("FormatError_DuplicatedKeyInSwitchMappings", resourceCulture);
            }
        }
    }
}
